programs:
  sleeper:
    cmd: "/bin/sleep 60"
    autostart: true
    stopsignal: INT        # Envoie SIGINT au lieu de SIGTERM
    stoptime: 3            # Attend 3 secondes avant de forcer l'arrÃªt avec SIGKILL
    numprocs: 1
    stdout: "/tmp/sleeper_out.log"
    stderr: "/tmp/sleeper_err.log"
